In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

## Simple Linear Regression

In [2]:
df = pd.read_csv('placement.csv')
df.head()

,cgpa,package
0,6.89,3.26
1,5.12,1.98
2,7.82,3.25
3,7.42,3.67
4,6.94,3.57


In [3]:
df.shape

(200, 2)

In [4]:
X = df['cgpa'].values
y = df['package'].values

In [5]:
X

array([6.89, 5.12, 7.82, 7.42, 6.94, 7.89, 6.73, 6.75, 6.09, 8.31, 5.32,
       6.61, 8.94, 6.93, 7.73, 7.25, 6.84, 5.38, 6.94, 7.48, 7.28, 6.85,
       6.14, 6.19, 6.53, 7.28, 8.31, 5.42, 5.94, 7.15, 7.36, 8.1 , 6.96,
       6.35, 7.34, 6.87, 5.99, 5.9 , 8.62, 7.43, 9.38, 6.89, 5.95, 7.66,
       5.09, 7.87, 6.07, 5.84, 8.63, 8.87, 9.58, 9.26, 8.37, 6.47, 6.86,
       8.2 , 5.84, 6.6 , 6.92, 7.56, 5.61, 5.48, 6.34, 9.16, 7.36, 7.6 ,
       5.11, 6.51, 7.56, 7.3 , 5.79, 7.47, 7.78, 8.44, 6.85, 6.97, 6.94,
       8.99, 6.59, 7.18, 7.63, 6.1 , 5.58, 8.44, 4.26, 4.79, 7.61, 8.09,
       4.73, 6.42, 7.11, 6.22, 7.9 , 6.79, 5.83, 6.63, 7.11, 5.98, 7.69,
       6.61, 7.95, 6.71, 5.13, 7.05, 7.62, 6.66, 6.13, 6.33, 7.76, 7.77,
       8.18, 5.42, 8.58, 6.94, 5.84, 8.35, 9.04, 7.12, 7.4 , 7.39, 5.23,
       6.5 , 5.12, 5.1 , 6.06, 7.33, 5.91, 6.78, 7.93, 7.29, 6.68, 6.37,
       5.84, 6.05, 7.2 , 6.1 , 5.64, 7.14, 7.91, 7.19, 7.91, 6.76, 6.93,
       4.85, 6.17, 5.84, 6.07, 5.66, 7.57, 8.28, 6.

In [6]:
y

array([3.26, 1.98, 3.25, 3.67, 3.57, 2.99, 2.6 , 2.48, 2.31, 3.51, 1.86,
       2.6 , 3.65, 2.89, 3.42, 3.23, 2.35, 2.09, 2.98, 2.83, 3.16, 2.93,
       2.3 , 2.48, 2.71, 3.65, 3.42, 2.16, 2.24, 3.49, 3.26, 3.89, 3.08,
       2.73, 3.42, 2.87, 2.84, 2.43, 4.36, 3.33, 4.02, 2.7 , 2.54, 2.76,
       1.86, 3.58, 2.26, 3.26, 4.09, 4.62, 4.43, 3.79, 4.11, 2.61, 3.09,
       3.39, 2.74, 1.94, 3.09, 3.31, 2.19, 1.61, 2.09, 4.25, 2.92, 3.81,
       1.63, 2.89, 2.99, 2.94, 2.35, 3.34, 3.62, 4.03, 3.44, 3.28, 3.15,
       4.6 , 2.21, 3.  , 3.44, 2.2 , 2.17, 3.49, 1.53, 1.48, 2.77, 3.55,
       1.48, 2.72, 2.66, 2.14, 4.  , 3.08, 2.42, 2.79, 2.61, 2.84, 3.83,
       3.24, 4.14, 3.52, 1.37, 3.  , 3.74, 2.82, 2.19, 2.59, 3.54, 4.06,
       3.76, 2.25, 4.1 , 2.37, 1.87, 4.21, 3.33, 2.99, 2.88, 2.65, 1.73,
       3.02, 2.01, 2.3 , 2.31, 3.16, 2.6 , 3.11, 3.34, 3.12, 2.49, 2.01,
       2.48, 2.58, 2.83, 2.6 , 2.1 , 3.13, 3.89, 2.4 , 3.15, 3.18, 3.04,
       1.54, 2.42, 2.18, 2.46, 2.21, 3.4 , 3.67, 2.

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [8]:
X_train.shape, y_train.shape

((160,), (160,))

In [9]:
X_test.shape, y_test.shape

((40,), (40,))

In [10]:
class SimpleLinearRegression:
    
    def __init__(self):
        self.m = None
        self.b = None
    
    def train(self, X_train, y_train):
        X_hat = np.mean(X_train)
        y_hat = np.mean(y_train)

        num, denom = 0, 0

        for i in range(X_train.shape[0]):
            num += (y_train[i] - y_hat)*(X_train[i] - X_hat)
            denom += (X_train[i] - X_hat)**2
        
        self.m = num/denom
        self.b = y_hat - self.m * X_hat
        
        print('Slope: ', self.m)
        print('Intercept: ', self.b)
    
    def predict(self, X_test):
        return self.m*X_test + self.b

In [11]:
lr = SimpleLinearRegression()
lr.train(X_train, y_train)

Slope:  0.5742564727019197
Intercept:  -1.0270069374542108


In [12]:
lr2 = LinearRegression()
lr2.fit(X_train.reshape(-1, 1), y_train)

print('Slope (with scikit-learn): ', lr2.coef_)
print('Intercept (with scikit-learn): ', lr2.intercept_)

Slope (with scikit-learn):  [0.57425647]
Intercept (with scikit-learn):  -1.0270069374542108


In [13]:
print(X_test[0], y_test[0])

6.63 2.79


In [14]:
lr.predict(X_test[0])

np.float64(2.7803134765595168)

In [15]:
lr2.predict(X_test[0].reshape(-1, 1))

array([2.78031348])

In [16]:
y_pred = lr.predict(X_test)

In [17]:
error = np.mean((y_test - y_pred)**2)
print(error)

0.08417638361329656


In [18]:
print('MSE: ', mean_squared_error(y_test, y_pred))

MSE:  0.08417638361329656


In [19]:
lr2_y_pred = lr2.predict(X_test.reshape(-1, 1))
print('MSE (with scikit-learn): ', mean_squared_error(y_test, lr2_y_pred))

MSE (with scikit-learn):  0.08417638361329656


## Multiple Linear Regression

In [20]:
from sklearn.datasets import load_diabetes

In [21]:
X, y = load_diabetes(return_X_y=True)

In [22]:
print(X)

[[ 0.03807591  0.05068012  0.06169621 ... -0.00259226  0.01990749
  -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 ... -0.03949338 -0.06833155
  -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 ... -0.00259226  0.00286131
  -0.02593034]
 ...
 [ 0.04170844  0.05068012 -0.01590626 ... -0.01107952 -0.04688253
   0.01549073]
 [-0.04547248 -0.04464164  0.03906215 ...  0.02655962  0.04452873
  -0.02593034]
 [-0.04547248 -0.04464164 -0.0730303  ... -0.03949338 -0.00422151
   0.00306441]]


In [23]:
print(y)

[151.  75. 141. 206. 135.  97. 138.  63. 110. 310. 101.  69. 179. 185.
 118. 171. 166. 144.  97. 168.  68.  49.  68. 245. 184. 202. 137.  85.
 131. 283. 129.  59. 341.  87.  65. 102. 265. 276. 252.  90. 100.  55.
  61.  92. 259.  53. 190. 142.  75. 142. 155. 225.  59. 104. 182. 128.
  52.  37. 170. 170.  61. 144.  52. 128.  71. 163. 150.  97. 160. 178.
  48. 270. 202. 111.  85.  42. 170. 200. 252. 113. 143.  51.  52. 210.
  65. 141.  55. 134.  42. 111.  98. 164.  48.  96.  90. 162. 150. 279.
  92.  83. 128. 102. 302. 198.  95.  53. 134. 144. 232.  81. 104.  59.
 246. 297. 258. 229. 275. 281. 179. 200. 200. 173. 180.  84. 121. 161.
  99. 109. 115. 268. 274. 158. 107.  83. 103. 272.  85. 280. 336. 281.
 118. 317. 235.  60. 174. 259. 178. 128.  96. 126. 288.  88. 292.  71.
 197. 186.  25.  84.  96. 195.  53. 217. 172. 131. 214.  59.  70. 220.
 268. 152.  47.  74. 295. 101. 151. 127. 237. 225.  81. 151. 107.  64.
 138. 185. 265. 101. 137. 143. 141.  79. 292. 178.  91. 116.  86. 122.
  72. 

In [24]:
X.shape

(442, 10)

In [25]:
y.shape

(442,)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [27]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(353, 10) (353,)
(89, 10) (89,)


In [28]:
class MultipleLinearRegression:
    
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None
    
    def train(self, X_train, y_train):
        X_train = np.insert(X_train, 0, 1, axis=1)
        weights = np.linalg.inv(np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        
        self.intercept_ = weights[0]
        self.coef_ = weights[1:]

        print('Weights: ', self.coef_)
        print('Intercept: ', self.intercept_)
    
    def predict(self, X_test):
        return np.dot(X_test, self.coef_) + self.intercept_

In [29]:
mlr = MultipleLinearRegression()
mlr.train(X_train, y_train)

Weights:  [  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588
  518.06227698  163.41998299  275.31790158  736.1988589    48.67065743]
Intercept:  151.34560453986003


In [30]:
mlr2 = LinearRegression()
mlr2.fit(X_train, y_train)
print(mlr2.coef_)
print(mlr2.intercept_)

[  37.90402135 -241.96436231  542.42875852  347.70384391 -931.48884588
  518.06227698  163.41998299  275.31790158  736.1988589    48.67065743]
151.34560453985995


In [31]:
y_test[0]

np.float64(219.0)

In [32]:
mlr.predict(X_test[0])

np.float64(139.54755840379613)

In [33]:
mlr2.predict(X_test[0].reshape(-1, 10))

array([139.5475584])

In [34]:
y_pred = mlr.predict(X_test)
y_pred

array([139.5475584 , 179.51720835, 134.03875572, 291.41702925,
       123.78965872,  92.1723465 , 258.23238899, 181.33732057,
        90.22411311, 108.63375858,  94.13865744, 168.43486358,
        53.5047888 , 206.63081659, 100.12925869, 130.66657085,
       219.53071499, 250.7803234 , 196.3688346 , 218.57511815,
       207.35050182,  88.48340941,  70.43285917, 188.95914235,
       154.8868162 , 159.36170122, 188.31263363, 180.39094033,
        47.99046561, 108.97453871, 174.77897633,  86.36406656,
       132.95761215, 184.53819483, 173.83220911, 190.35858492,
       124.4156176 , 119.65110656, 147.95168682,  59.05405241,
        71.62331856, 107.68284704, 165.45365458, 155.00975931,
       171.04799096,  61.45761356,  71.66672581, 114.96732206,
        51.57975523, 167.57599528, 152.52291955,  62.95568515,
       103.49741722, 109.20751489, 175.64118426, 154.60296242,
        94.41704366, 210.74209145, 120.2566205 ,  77.61585399,
       187.93203995, 206.49337474, 140.63167076, 105.59

In [35]:
print('MSE: ', mean_squared_error(y_test, y_pred))
print('R2 Score: ', r2_score(y_test, y_pred))

MSE:  2900.193628493479
R2 Score:  0.4526027629719199


In [36]:
mlr2_y_pred = mlr2.predict(X_test)
print('MSE (scikit-learn): ', mean_squared_error(y_test, mlr2_y_pred))
print('R2 Score (scikit-learn): ', r2_score(y_test, mlr2_y_pred))

MSE (scikit-learn):  2900.193628493482
R2 Score (scikit-learn):  0.4526027629719195
